openapi: 3.0.3
info:
  title: api.dumbphoneapps.com
  description: This is the swagger definition for dumbphoneapps.com api
  version: 0.0.1
paths:
  /send-otp:
    post:
      summary: submit a phone number to receive a one time passcode
      security: []
      operationId: generate_and_send_otp
      requestBody:
        description: send the phone number you want to receive your one time passcode on
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                phone:
                  type: string
                  example: '5551234567'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
  /login:
    post:
      summary: log in with your phone number and one time pass code, and receive a temporary API token in response
      security: []
      operationId: submit_otp
      requestBody:
        description: log in to the server with your phone number and one time pass code
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                  example: '5551234567'
                otp:
                  type: string
                  example: '1234567'
      responses:
        '200':
          description: Successful operation
          headers:
            X-dumbphone-auth-token:
              schema:
                type: string
              description: temporary token used to access the API
              example: 'abcdef1234567890abcdef1234567890'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
  /list:
    get:
      summary: retrieve the list data for a given user
      parameters:
        - in: header
          name: X-dumbphone-auth
          schema:
            type: string
      operationId: get_list_data
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListArray'
components:
  schemas:
    Response:
      type: object
      properties:
        status:
          type: string
          description: status of order submission
          example: success
          enum:
            - success
            - failed
        message:
          type: string
          description: detailed information pertaining to the status of the message
          example: 'Successfully called the API'
    LoginResponse:
      allOf:
        - $ref: '#/components/schemas/Response'
      type: object
      properties:
        csrf-token:
          type: string
          description: temporary csrf token used to access the API
          example: 'abcdef1234567890abcdef1234567890'
    List:
      type: object
      properties:
        name:
          type: string
        hash:
          type: string
        list-items:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              hash:
                type: string
              crossed-off:
                type: boolean
    ListArray:
      type: array
      items:
        $ref: '#/components/schemas/List'
        