# Generated by Django 4.1.3 on 2022-11-17 00:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('hash', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Random UUID representing this particular food')),
                ('name', models.TextField(verbose_name='Human readable title for this particular food')),
                ('metadata', models.JSONField(verbose_name='either a JSON representing the macronutrition of the food, or a JSON representing a recipe for this particular food')),
            ],
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('hash', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Random UUID representing this diary entry')),
                ('quantity', models.FloatField(default=1.0, verbose_name='The amount ingested of the food specified in the food_hash column')),
                ('time_stamp', models.DateTimeField(default=datetime.datetime(2022, 11, 16, 19, 34, 14, 843689), editable=False, verbose_name='time the entry was created')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fooddiary.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
