# Generated by Django 4.1.3 on 2022-11-17 01:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddiary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 20, 2, 16, 470877), editable=False, verbose_name='time the entry was created'),
        ),
        migrations.AlterField(
            model_name='food',
            name='metadata',
            field=models.TextField(verbose_name='either a JSON representing the macronutrition of the food, or a JSON representing a recipe for this particular food'),
        ),
    ]
