# Generated by Django 4.1.3 on 2022-12-06 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddiary', '0003_diaryentry_serving_alter_diaryentry_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='time the entry was created'),
        ),
    ]
