# Generated by Django 4.1.5 on 2023-03-16 23:49

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListGroup',
            fields=[
                ('hash', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Random UUID representing this list entry')),
                ('time_stamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='time the entry was created')),
                ('encrypted_text', models.BinaryField(editable=True, verbose_name='The encrypted text to be stored')),
            ],
        ),
    ]
