# Generated by Django 4.1.5 on 2023-03-17 16:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('securenotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('hash', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Random UUID representing this list entry')),
                ('time_stamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='time the entry was created')),
                ('encrypted_text', models.BinaryField(editable=True, verbose_name='The encrypted text to be stored')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
