# Generated by Django 4.1.5 on 2023-03-16 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securenotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListGroup',
            new_name='Notes',
        ),
    ]
