angularCards = [

  // &#9472;&#9472; 1. BASICS / SYNTAX &#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;

    { "exam": "interview", "front": "What is a signal in Angular? How do you read it and write to it?", "back": "A signal is a reactive value holder. Read it by calling it as a function: <code>this.count()</code>. Write with <code>.set(newValue)</code> or <code>.update(prev => newValue)</code>. Equivalent to React's <code>useState</code>." }
  , { "exam": "interview", "front": "What is the difference between <code>signal.set()</code> and <code>signal.update()</code>?", "back": "<code>.set(val)</code> &#8212; use when you already know the new value and don't need the old one.<br><code>.update(prev => val)</code> &#8212; use when the new value depends on the current one, e.g. <code>count.update(n => n + 1)</code> or toggling a boolean." }
  , { "exam": "interview", "front": "What is <code>computed()</code> and what React hook does it replace?", "back": "<code>computed()</code> derives a read-only value from one or more signals. It replaces <code>useMemo</code>. Re-runs automatically when any signal it reads changes. Example: <code>filtered = computed(() => this.all.filter(p => p.name.includes(this.query())))</code>" }
  , { "exam": "interview", "front": "How does <code>computed()</code> know which signals to watch? There is no dependency array.", "back": "Angular tracks dependencies at runtime. When a <code>computed()</code> or <code>effect()</code> runs, a hidden 'current consumer' is set. Every signal call (<code>this.query()</code>) during execution registers itself as a dependency. No array needed &#8212; Angular discovers what you actually read." }
  , { "exam": "interview", "front": "What is <code>effect()</code> and what React hook does it most closely replace?", "back": "<code>effect()</code> runs a side-effect whenever any signal it reads changes. Closest to <code>useEffect</code> with no dependency array. Common uses: syncing to localStorage, logging, starting/stopping timers. Must be called in an injection context (constructor or field initializer)." }
  , { "exam": "interview", "front": "What is <code>inject()</code> and what does it replace from React?", "back": "<code>inject(MyService)</code> retrieves a singleton service from Angular's DI system &#8212; equivalent to <code>useContext(MyContext)</code>. Must be called in an injection context. Example: <code>private auth = inject(AuthService)</code>" }
  , { "exam": "interview", "front": "What is a Service in Angular and what decorator marks it as injectable?", "back": "A Service is a plain TypeScript class decorated with <code>@Injectable</code>. It holds shared logic or state outside any component. Angular's DI system creates and manages the instance. Example: <code>@Injectable({ providedIn: 'root' })</code>" }
  , { "exam": "interview", "front": "What does <code>providedIn: 'root'</code> mean on a service?", "back": "It creates a single app-wide singleton &#8212; equivalent to a default Spring bean or a React Context at the root. Every component that injects it gets the exact same instance for the lifetime of the app." }
  , { "exam": "interview", "front": "What are the key fields of the <code>@Component</code> decorator?", "back": "<code>selector</code> &#8212; the HTML tag name (<code>app-home</code>)<br><code>templateUrl</code> / <code>template</code> &#8212; HTML file or inline string<br><code>styleUrl</code> / <code>styles</code> &#8212; CSS file or inline string<br><code>imports</code> &#8212; other components/directives/pipes this template uses (standalone)<br><code>changeDetection</code> &#8212; Default or OnPush" }
  , { "exam": "interview", "front": "What is a standalone component and what did it replace?", "back": "A standalone component declares its own <code>imports</code> directly on <code>@Component</code>, without needing an <code>NgModule</code>. It replaced the older module system where every component had to be declared in an <code>NgModule</code>'s <code>declarations</code> array. Available since Angular 14, default since Angular 17." }
  , { "exam": "interview", "front": "What is the <code>selector</code> field in <code>@Component</code> used for?", "back": "It defines the HTML tag used to render the component. <code>selector: 'app-nav'</code> means you write <code>&lt;app-nav /&gt;</code> in a parent template. Convention: prefix with <code>app-</code> to avoid collisions with native HTML elements." }
  , { "exam": "interview", "front": "What is the Angular syntax for event binding and property binding?", "back": "Event binding (like React's onClick): <code>(click)=\"handler()\"</code><br>Property binding (like React's prop): <code>[src]=\"imageUrl\"</code><br>Two-way binding: <code>[(ngModel)]=\"value\"</code><br>The rule: parentheses = output (events), brackets = input (props)." }
  , { "exam": "interview", "front": "What does <code>{{ value }}</code> do in an Angular template?", "back": "Template interpolation &#8212; outputs the string value of an expression. Equivalent to <code>{value}</code> in JSX. If <code>value</code> is a signal, you must call it: <code>{{ count() }}</code>. Angular HTML-escapes the output automatically." }
  , { "exam": "interview", "front": "What does <code>[class.active]=\"condition\"</code> do?", "back": "Conditionally adds or removes the CSS class <code>active</code> based on whether <code>condition</code> is truthy. Equivalent to React's <code>className={condition ? 'active' : ''}</code>. You can also bind multiple classes with <code>[ngClass]</code>." }
  , { "exam": "interview", "front": "What is <code>routerLink</code> and what does it replace from React?", "back": "<code>routerLink</code> is a directive that creates client-side navigation links &#8212; equivalent to React Router's <code>&lt;Link to='/path'&gt;</code>. Usage: <code>&lt;a routerLink=\"/blog\"&gt;</code>. Must import <code>RouterLink</code> in the component's <code>imports</code> array." }

  // &#9472;&#9472; 2. TEMPLATES & CONTROL FLOW &#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;

  , { "exam": "interview", "front": "What is the Angular 17+ syntax for conditional rendering?", "back": "<code>@if (condition) { ... } @else { ... }</code><br>Replaces the older <code>*ngIf</code> directive. Equivalent to <code>{condition ? &lt;A/&gt; : &lt;B/&gt;}</code> in React. Can also use <code>@else if</code> for chains." }
  , { "exam": "interview", "front": "What is the <code>@for</code> syntax and why is <code>track</code> required?", "back": "<code>@for (item of items; track item.id) { ... }</code><br><code>track</code> is Angular's equivalent of React's <code>key</code> prop &#8212; it tells Angular how to identify items so it can surgically update the DOM instead of re-rendering the whole list. Omitting it causes a compile error in strict mode." }
  , { "exam": "interview", "front": "What is the Angular 17+ syntax for a switch statement in a template?", "back": "<code>@switch (status) {<br>  @case ('loading') { &lt;spinner/&gt; }<br>  @case ('error') { &lt;error/&gt; }<br>  @default { &lt;content/&gt; }<br>}</code><br>Replaces the older <code>*ngSwitch</code> directive pattern." }
  , { "exam": "interview", "front": "What is the difference between <code>href=\"/path\"</code> and <code>[href]=\"url\"</code> in Angular?", "back": "<code>href=\"/path\"</code> &#8212; static string, hardcoded in the HTML.<br><code>[href]=\"url\"</code> &#8212; property binding, evaluates <code>url</code> as a TypeScript expression from the component class. The brackets mean 'evaluate this as code, not a string'." }
  , { "exam": "interview", "front": "What is <code>[(ngModel)]</code> and what module do you need to use it?", "back": "<code>[(ngModel)]</code> is two-way data binding for form inputs &#8212; it both sets the input's value and updates a component property when the user types. Requires <code>FormsModule</code> in the component's <code>imports</code>. The <code>[()]</code> syntax is called 'banana in a box'." }
  , { "exam": "interview", "front": "What is a template reference variable in Angular?", "back": "Declared with <code>#name</code> on an element: <code>&lt;input #searchInput /&gt;</code>. Gives you a reference to the DOM element or component instance directly in the template. Access it in handlers: <code>(click)=\"doSearch(searchInput.value)\"</code>. In the class, use <code>@ViewChild</code>." }
  , { "exam": "interview", "front": "What is <code>@defer</code> in Angular and when would you use it?", "back": "<code>@defer</code> lazily loads a block of template (and its component dependencies) only when needed. Triggers: <code>@defer (on viewport)</code>, <code>on interaction</code>, <code>on idle</code>, etc. Use it for below-the-fold content, heavy components, or anything not needed on initial load. Different from lazy routes &#8212; it works at the template level." }
  , { "exam": "interview", "front": "What is a pipe in Angular? Give an example.", "back": "A pipe transforms a value in a template: <code>{{ date | date:'shortDate' }}</code> or <code>{{ name | uppercase }}</code>. Built-in pipes include <code>date</code>, <code>currency</code>, <code>async</code>, <code>json</code>. Create custom pipes with <code>@Pipe({ name: 'myPipe' })</code>." }
  , { "exam": "interview", "front": "What is <code>ng-content</code> used for?", "back": "<code>ng-content</code> is Angular's content projection &#8212; equivalent to React's <code>children</code> prop. Whatever you put between a component's tags gets rendered where <code>&lt;ng-content /&gt;</code> appears in that component's template. Supports multiple named slots with <code>select</code>." }
  , { "exam": "interview", "front": "What is <code>@ViewChild</code> used for?", "back": "<code>@ViewChild(MyComponent) child!: MyComponent</code> gives the class a reference to a child component or DOM element. Available after <code>ngAfterViewInit</code>. Use it to call methods on a child, read its properties, or interact with a native element. Equivalent to React's <code>useRef</code> on a child component." }

  // &#9472;&#9472; 3. LIFECYCLE HOOKS &#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;

  , { "exam": "interview", "front": "What are the main Angular lifecycle hooks in order?", "back": "1. <code>constructor</code> &#8212; DI only, no inputs available<br>2. <code>ngOnChanges</code> &#8212; input values change<br>3. <code>ngOnInit</code> &#8212; after first render, inputs available<br>4. <code>ngAfterViewInit</code> &#8212; child views ready<br>5. <code>ngOnDestroy</code> &#8212; component being removed" }
  , { "exam": "interview", "front": "What is <code>ngOnInit</code> equivalent to in React?", "back": "<code>useEffect(() => { ... }, [])</code> &#8212; runs once after the component mounts. In Angular it's a named method on the class that you declare by implementing the <code>OnInit</code> interface. Use it for initial data fetching, subscriptions, and setup that needs inputs to be available." }
  , { "exam": "interview", "front": "What are three good uses of <code>ngOnDestroy</code>?", "back": "1. <code>subscription.unsubscribe()</code> &#8212; stop an Observable to prevent memory leaks<br>2. <code>clearInterval(this.timer)</code> &#8212; stop a running interval<br>3. <code>window.removeEventListener(...)</code> &#8212; remove manually added event listeners<br>General rule: clean up anything you started in ngOnInit that would outlive the component." }
  , { "exam": "interview", "front": "What triggers <code>ngOnChanges</code>?", "back": "It fires when a parent component changes a value passed via <code>@Input()</code>. Receives a <code>SimpleChanges</code> object with previous and current values. Equivalent to <code>useEffect(() => {}, [prop])</code>. Does NOT fire for mutations inside an object &#8212; only when the input reference itself changes." }
  , { "exam": "interview", "front": "What is the difference between the constructor and <code>ngOnInit</code>?", "back": "Constructor: runs during DI instantiation. Use ONLY for injecting services. Inputs are not yet set, the template is not rendered.<br>ngOnInit: runs after Angular sets all <code>@Input()</code> values and renders the view. Put all initialization logic here, not in the constructor." }
  , { "exam": "interview", "front": "When would you NOT put critical logic in <code>ngOnDestroy</code>?", "back": "When the logic is critical for data integrity &#8212; like saving a shopping cart or submitting a form. ngOnDestroy may not fire if the browser tab is closed or the page crashes. Use a CanDeactivate route guard for 'are you sure you want to leave?' flows, and auto-save on change for persistent data." }
  , { "exam": "interview", "front": "What is <code>takeUntilDestroyed()</code> and what problem does it solve?", "back": "An RxJS operator that automatically completes a subscription when the component is destroyed &#8212; eliminating the need to manually call <code>unsubscribe()</code> in <code>ngOnDestroy</code>. Usage: <code>this.http.get(url).pipe(takeUntilDestroyed()).subscribe(...)</code>. Available from <code>@angular/core/rxjs-interop</code>, Angular 16+." }
  , { "exam": "interview", "front": "What is <code>DestroyRef</code>?", "back": "An injectable token (Angular 16+) that represents the component's lifetime. You can register cleanup callbacks on it: <code>inject(DestroyRef).onDestroy(() => cleanup())</code>. Powers <code>takeUntilDestroyed()</code> under the hood. Lets you write cleanup logic anywhere (not just in the component class) as long as you have the DestroyRef." }

  // &#9472;&#9472; 4. SERVICES, DI & STATE &#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;

  , { "exam": "interview", "front": "What is the difference between <code>providedIn: 'root'</code> and <code>providers: [MyService]</code> on a component?", "back": "<code>providedIn: 'root'</code> &#8212; one app-wide singleton, shared by everything.<br><code>providers: [MyService]</code> on a component &#8212; a NEW instance is created for that component and its children, and destroyed when the component is destroyed. Use this when each instance of a component needs its own isolated state." }
  , { "exam": "interview", "front": "How do you scope a service to a specific component subtree?", "back": "Add the service to the <code>providers</code> array of the parent component: <code>@Component({ providers: [CartService] })</code>. Angular creates a new instance for that component and all its descendants. When the component is destroyed, so is the service instance." }
  , { "exam": "interview", "front": "If two different components both inject the same service, do they get the same instance?", "back": "Yes &#8212; if the service is <code>providedIn: 'root'</code>, all injectors share one singleton. The exception is if either component (or an ancestor) provides the service in its own <code>providers</code> array, which creates a new scoped instance for that subtree." }
  , { "exam": "interview", "front": "What is the conceptual difference between a service and a signal?", "back": "A signal is a reactive value &#8212; it holds data and notifies readers when it changes.<br>A service is a class &#8212; it can hold signals, methods, business logic, and inject other services.<br>Services are often the right place TO PUT signals that need to be shared across components." }
  , { "exam": "interview", "front": "When should state live in a service vs a local component signal?", "back": "Local signal: state only used by one component (e.g. a form's loading spinner, a toggle).<br>Service signal: state shared across multiple components (e.g. current user, a cart, search query). Rule: if two components need to read or write the same value, put it in a service." }
  , { "exam": "interview", "front": "Can two sibling components share state without a common parent? How?", "back": "Yes &#8212; put the shared state in a <code>providedIn: 'root'</code> service. Both siblings inject it and they both read/write the same signal. No prop drilling, no context provider needed. This is the Angular answer to the React 'lift state up' pattern." }
  , { "exam": "interview", "front": "What is the Angular DI hierarchy?", "back": "Angular has a tree of injectors mirroring the component tree. When a component asks for a service, Angular walks UP the tree looking for a provider: component &#8594; parent &#8594; ... &#8594; root. The first matching provider wins. This is what makes component-level <code>providers</code> override the root singleton." }
  , { "exam": "interview", "front": "What is a DI token in Angular?", "back": "A token is the key Angular uses to look up a dependency. Usually the class itself is the token: <code>inject(AuthService)</code>. But you can also use string or <code>InjectionToken</code> objects as tokens &#8212; useful for injecting primitive values or interfaces." }
  , { "exam": "interview", "front": "What is <code>InjectionToken</code> used for?", "back": "It creates a typed token for injecting values that aren't classes &#8212; like config objects, feature flags, or API URLs. Example: <code>const API_URL = new InjectionToken&lt;string&gt;('apiUrl')</code>. Then provide it: <code>{ provide: API_URL, useValue: 'https://api.example.com' }</code> and inject it: <code>inject(API_URL)</code>." }
  , { "exam": "interview", "front": "How does Angular's DI compare to Spring's bean scopes?", "back": "<code>providedIn: 'root'</code> = Spring singleton (default) &#8212; one instance for the app.<br>Component <code>providers: []</code> = Spring prototype &#8212; new instance per component mount.<br>Angular has no direct equivalent to Spring's request or session scope, but route-level providers approximate request scope." }

  // &#9472;&#9472; 5. CHANGE DETECTION &#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;

  , { "exam": "interview", "front": "What are the two change detection strategies in Angular?", "back": "<code>ChangeDetectionStrategy.Default</code> &#8212; Angular checks the entire component tree on every browser event (click, timer, HTTP response). Safe but potentially slow for large apps.<br><code>ChangeDetectionStrategy.OnPush</code> &#8212; Angular only checks the component when an @Input reference changes, an event originates inside it, or a signal it reads changes." }
  , { "exam": "interview", "front": "What does <code>OnPush</code> do and when should you use it?", "back": "OnPush tells Angular to skip re-checking a component unless it has a reason to. Use it on components with no or stable inputs &#8212; especially 'display' components that just render data. With signals, OnPush is automatically respected: signal changes always trigger a re-check regardless of strategy. It's a free performance win for leaf components." }
  , { "exam": "interview", "front": "What is zone.js and what role does it play in Angular?", "back": "zone.js patches browser APIs (setTimeout, Promise, click events) so Angular knows when async operations complete and triggers change detection. Without it, Angular wouldn't know when to re-render after an HTTP call or timer. In Angular 18+ you can opt out with 'zoneless' mode and use signals exclusively instead." }
  , { "exam": "interview", "front": "With signals, do you still need <code>OnPush</code> change detection?", "back": "Signals work correctly with both Default and OnPush. With signals, Angular can track exactly which component reads which signal and update only that part of the view &#8212; so OnPush becomes less critical. That said, OnPush is still a good practice for non-signal components and is a free optimization." }
  , { "exam": "interview", "front": "What triggers change detection in Default mode?", "back": "Any async event that zone.js intercepts: user events (click, input, keydown), HTTP responses, setTimeout/setInterval callbacks, Promise resolutions. Angular then checks the ENTIRE component tree from root to leaf." }
  , { "exam": "interview", "front": "What triggers change detection in OnPush mode?", "back": "1. An <code>@Input()</code> property receives a new reference (not a mutation).<br>2. An event fires from inside the component itself.<br>3. A signal the component reads emits a new value.<br>4. The async pipe resolves a new value.<br>5. <code>ChangeDetectorRef.markForCheck()</code> is called manually." }

  // &#9472;&#9472; 6. ROUTING &#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;

  , { "exam": "interview", "front": "How do you read a route parameter in Angular?", "back": "Inject <code>ActivatedRoute</code> and read from <code>paramMap</code>: <code>inject(ActivatedRoute).paramMap.pipe(map(p => p.get('id')))</code>. This returns an Observable. Convert to a signal with <code>toSignal()</code> so you can use it in <code>computed()</code>. For a one-time read: <code>this.route.snapshot.paramMap.get('id')</code>." }
  , { "exam": "interview", "front": "What is the difference between reading params via snapshot vs Observable?", "back": "<code>snapshot.paramMap.get('id')</code> &#8212; reads the param once at the time the component loads. Simple, but stale if the route param changes while the component is still alive (e.g. navigating from /projects/1 to /projects/2 without destroying the component).<br>Observable paramMap &#8212; reactive, updates whenever the param changes. Prefer this for detail pages." }
  , { "exam": "interview", "front": "What is a route guard in Angular? Name the main types.", "back": "A guard is a function that runs before a route activates or deactivates, and can block or redirect navigation.<br><code>canActivate</code> &#8212; can the user enter this route? (auth checks)<br><code>canDeactivate</code> &#8212; can the user leave? (unsaved changes warning)<br><code>canMatch</code> &#8212; should this route even be considered?<br><code>resolve</code> &#8212; fetch data before the route activates" }
  , { "exam": "interview", "front": "What is <code>canDeactivate</code> used for?", "back": "It runs before the user navigates AWAY from a route. Return <code>false</code> to block navigation, <code>true</code> to allow. Common use: 'You have unsaved changes &#8212; are you sure you want to leave?' The better alternative to putting save logic in ngOnDestroy." }
  , { "exam": "interview", "front": "What is a route resolver?", "back": "A resolver pre-fetches data before a route's component is created. The component only renders once the data is ready &#8212; no loading spinner needed inside the component. Configure with <code>resolve: { posts: postsResolver }</code> on the route, then read with <code>this.route.data</code>." }
  , { "exam": "interview", "front": "What is lazy loading in Angular and how do you configure it?", "back": "Lazy loading defers downloading a component's bundle until the user navigates to that route. Configure with <code>loadComponent</code>: <code>{ path: 'blog', loadComponent: () => import('./blog').then(m => m.Blog) }</code>. Angular creates a separate JS chunk per lazy route. Reduces initial bundle size." }
  , { "exam": "interview", "front": "What is <code>routerLinkActive</code>?", "back": "A directive that adds a CSS class to a link when its route is currently active: <code>&lt;a routerLink=\"/blog\" routerLinkActive=\"active\"&gt;</code>. Add <code>[routerLinkActiveOptions]=\"{ exact: true }\"</code> for the home route to prevent it matching every URL." }
  , { "exam": "interview", "front": "What is the difference between <code>router.navigate()</code> and <code>router.navigateByUrl()</code>?", "back": "<code>navigate(['/projects', id])</code> &#8212; takes an array of path segments, supports relative navigation and query params as options. Preferred.<br><code>navigateByUrl('/projects/1')</code> &#8212; takes a full URL string, always absolute. Use for redirects where you have a complete URL." }

  // &#9472;&#9472; 7. RXJS &#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;

  , { "exam": "interview", "front": "What is an Observable and how is it different from a Promise?", "back": "A Promise resolves once with one value. An Observable is a stream that can emit zero, one, or many values over time, and can be cancelled. Observables are lazy &#8212; nothing happens until you <code>subscribe()</code>. Angular uses Observables for HTTP, routing, and forms because they can be cancelled and composed." }
  , { "exam": "interview", "front": "What does <code>subscribe()</code> do? What are its three callbacks?", "back": "<code>subscribe()</code> starts executing an Observable. Three callbacks: <code>next(value)</code> &#8212; called for each emitted value, <code>error(err)</code> &#8212; called on failure (stream ends), <code>complete()</code> &#8212; called when the stream finishes normally. Always store the return value (a Subscription) so you can unsubscribe." }
  , { "exam": "interview", "front": "What does the RxJS <code>map()</code> operator do?", "back": "Transforms each emitted value, like <code>Array.map</code> but for a stream. Example: <code>this.route.paramMap.pipe(map(p => p.get('id')))</code> &#8212; turns a paramMap object into just the id string. Commonly used to extract data from HTTP responses." }
  , { "exam": "interview", "front": "What does <code>switchMap()</code> do and when would you use it over <code>mergeMap()</code>?", "back": "<code>switchMap</code> maps to a new Observable and CANCELS the previous inner Observable. Use it for search inputs &#8212; if the user types before the last request finishes, switchMap cancels the old HTTP request and starts a new one. <code>mergeMap</code> runs all inner Observables concurrently without cancelling. Use mergeMap when order and cancellation don't matter." }
  , { "exam": "interview", "front": "What does <code>toSignal()</code> do?", "back": "<code>toSignal(observable)</code> (from <code>@angular/core/rxjs-interop</code>) converts an RxJS Observable into a signal. Lets you use Observable-based APIs (like the router's paramMap or HTTP calls) in signal-based computed() or directly in templates. Automatically unsubscribes when the component is destroyed." }
  , { "exam": "interview", "front": "What happens if you subscribe to an Observable and never unsubscribe?", "back": "Memory leak. The subscription and its callback keep a reference to the component alive even after the component is destroyed. If the Observable keeps emitting, it will try to update state on a dead component. Fix: use <code>takeUntilDestroyed()</code>, the async pipe, or manually call <code>unsubscribe()</code> in ngOnDestroy." }
  , { "exam": "interview", "front": "What is the async pipe and why is it useful?", "back": "<code>{{ observable$ | async }}</code> subscribes to an Observable (or Promise) in the template and automatically unsubscribes when the component is destroyed &#8212; no manual subscribe/unsubscribe needed. Works with OnPush change detection. Downsides: creates multiple subscriptions if used multiple times for the same observable &#8212; use <code>@let</code> or share the observable." }

  // &#9472;&#9472; 8. FORMS &#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;

  , { "exam": "interview", "front": "What are the two approaches to forms in Angular?", "back": "<b>Template-driven forms</b>: form logic lives in the HTML using <code>[(ngModel)]</code> and directives. Simple, less code, good for basic forms.<br><b>Reactive forms</b>: form logic lives in the TypeScript class using <code>FormControl</code> and <code>FormGroup</code>. More explicit, easier to test, required for complex validation or dynamic fields." }
  , { "exam": "interview", "front": "When would you choose Reactive Forms over Template-driven forms?", "back": "Use Reactive Forms when: you need custom validators, async validators (e.g. check if username is taken), dynamically add/remove fields, unit test the form logic, or combine form state with RxJS streams. Use Template-driven for simple contact forms or login forms with basic required/email validation." }
  , { "exam": "interview", "front": "What is a <code>FormControl</code>?", "back": "The atomic unit of a Reactive Form &#8212; tracks the value and validation state of a single input. <code>new FormControl('', Validators.required)</code>. Has properties: <code>.value</code>, <code>.valid</code>, <code>.dirty</code>, <code>.touched</code>, <code>.errors</code>. Exposes an Observable <code>.valueChanges</code> you can subscribe to." }
  , { "exam": "interview", "front": "What is a <code>FormGroup</code>?", "back": "A collection of <code>FormControl</code>s (or nested FormGroups) that are managed together. <code>new FormGroup({ email: new FormControl(''), password: new FormControl('') })</code>. Has the same valid/invalid/value properties as FormControl but aggregated. Bind to a form element with <code>[formGroup]=\"myForm\"</code>." }

  // &#9472;&#9472; 9. HTTP & INTERCEPTORS &#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;

  , { "exam": "interview", "front": "How do you make an HTTP GET request in Angular?", "back": "Inject <code>HttpClient</code> and call <code>this.http.get&lt;MyType&gt;('/api/data')</code>. Returns an Observable &#8212; nothing happens until you subscribe. Provide HttpClient by adding <code>provideHttpClient()</code> to <code>app.config.ts</code>. Subscribe: <code>.subscribe(data => this.items.set(data))</code> or convert with <code>toSignal()</code>." }
  , { "exam": "interview", "front": "What does <code>HttpClient.get()</code> return?", "back": "An Observable of the response body (typed if you provide a generic: <code>get&lt;User[]&gt;</code>). It's cold &#8212; no request is made until you <code>subscribe()</code> or use the async pipe. The Observable completes automatically after the single HTTP response, so no manual unsubscribe is needed for HTTP." }
  , { "exam": "interview", "front": "What is an HTTP interceptor and what is it used for?", "back": "An interceptor is a function that runs for every outgoing HTTP request and/or incoming response. Common uses: attach auth tokens to every request, log requests, handle 401 errors globally, show/hide a loading indicator, retry failed requests. It's Angular's equivalent of Axios interceptors." }
  , { "exam": "interview", "front": "How do you add an auth token to every HTTP request using an interceptor?", "back": "<code>export const authInterceptor: HttpInterceptorFn = (req, next) => {<br>  const token = inject(AuthService).token();<br>  const cloned = req.clone({ headers: req.headers.set('Authorization', 'Bearer ' + token) });<br>  return next(cloned);<br>};</code><br>Register in app.config: <code>provideHttpClient(withInterceptors([authInterceptor]))</code>" }

  // &#9472;&#9472; 10. INTERVIEW: WHEN TO USE WHAT &#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;&#9472;

  , { "exam": "interview", "front": "signal() vs Observable &#8212; when do you use each?", "back": "<b>Signal</b>: synchronous state that lives in a component or service &#8212; UI state, derived values, local toggles. Simple, no subscription management needed.<br><b>Observable</b>: async streams, HTTP calls, WebSockets, router events, anything that emits over time. Use <code>toSignal()</code> to bridge them when you need to combine with computed()." }
  , { "exam": "interview", "front": "How do you decide if state belongs in a service or a component?", "back": "One component needs it &#8594; component signal. Multiple components need to read OR write it &#8594; service. If you ever find yourself passing the same piece of state through more than one layer of @Input props, it should probably be in a service." }
  , { "exam": "interview", "front": "OnPush vs Default change detection &#8212; when does the choice actually matter?", "back": "It matters most in large apps with deep component trees and frequent events. In small apps the difference is negligible. OnPush is almost always the right default for presentational/leaf components that just display data. With signals throughout, the benefit is mostly automatic &#8212; but OnPush is still good practice and a common interview topic." }
  , { "exam": "interview", "front": "ngOnDestroy vs takeUntilDestroyed() &#8212; which is preferred in modern Angular?", "back": "<code>takeUntilDestroyed()</code> is preferred (Angular 16+). It's less boilerplate, works inline in the pipe chain, and doesn't require implementing the OnDestroy interface. Reserve <code>ngOnDestroy</code> for non-RxJS cleanup: clearing intervals, removing event listeners, closing WebSocket connections." }
  , { "exam": "interview", "front": "Reactive Forms vs Template-driven forms &#8212; what's the one-line decision rule?", "back": "If the form has complex/dynamic validation or you need to test the form logic in isolation &#8594; Reactive Forms. Otherwise &#8594; Template-driven. In practice, most production apps use Reactive Forms for consistency." }
  , { "exam": "interview", "front": "What is the difference between <code>@defer</code> and a lazy-loaded route?", "back": "Lazy route: defers loading an entire PAGE component until the user navigates to that URL. The granularity is the route.<br>@defer: defers loading a specific BLOCK within a template &#8212; a heavy widget, a chart, a comments section. Works at the template level within any page. You can have both: a lazy route that also uses @defer internally." }
  , { "exam": "interview", "front": "Why prefer <code>computed()</code> over a method call in a template for derived values?", "back": "A method in a template (<code>{{ getFiltered() }}</code>) re-runs EVERY change detection cycle, even if the inputs haven't changed. <code>computed()</code> is memoized &#8212; it only re-runs when a signal it reads actually changes. For expensive derivations (filtering large lists) this is a significant performance difference." }
  , { "exam": "interview", "front": "Standalone component vs NgModule &#8212; which should you use in a new project?", "back": "Standalone, always, for new projects in Angular 14+. NgModule is the legacy pattern &#8212; more boilerplate, harder to understand. Standalone components declare their own dependencies directly and compose with lazy routing naturally. You'll still encounter NgModules in existing codebases, but don't write new ones." }

];
