awsCards = [
  { "front": "What is Amazon Mechanical Turk?", "back": "A crowdsourcing marketplace where businesses (Requesters) hire a global, on-demand workforce (Workers) to complete small, discrete tasks, known as Human Intelligence Tasks (HITs), that computers struggle with, like image tagging, data verification, survey participation, and content moderation, by breaking large projects into manageable, paid micro-tasks. " },
  { "front": "Which target is NOT directly supported for AWS Step Functions?", "back": "Amazon Mechanical Turk" },
  { "front": "What is the purpose of a SQS FIFO queue?", "back": "They ensure messages are processed in the exact order they are sent" },
  { "front": "How can you order messages from a Kinesis Data Stream?", "back": "You can use <code>customer_id</code> as the partition key" },
  { "front": "How can you ensure SQS messages only occur once?", "back": "Code your application to be idempotent" },
  { "front": "What is Amazon MQ?", "back": "A managed message broker service, supporting popular engines like Apache ActiveMQ and RabbitMQ and standard APIs like JMS, AMQP, and MQTT, typically used to migrate on-prem apps to the cloud with minimal changes" },
  { "front": "How do you do a lift-and-shift deployment of an on-prem app that uses RabbitMQ?", "back": "Use Amazon MQ" },
  { "front": "How can SNS Access Policies be used?", "back": "If you want a SNS topic in one AWS account to be accessible in other AWS accounts, e.g. for a centralied messaging account." },
  { "front": "When going from SNS &rarr; fanout &rarr; SQS, how can you filter messages so they only go to one of the SQS queues?", "back": "Use SNS Message Filtering" },
  { "front": "What is SNS Message Filtering?", "back": "It allows subscribers to receive only relevant messages from a topic by applying a filter policy, which matches against message attributes or the message body (payload) to selectively deliver notifications" },
  { "front": "When you assume an IAM role, you (keep / lose) your current permissions", "back": "lose" },
  { "front": "From an app you're running in Account A, how can you access resources in Account B without losing the permissions you currently have?", "back": "Attach IAM permissions to the exisitng policy for your app in Account A, then add a policy to the resource in Account B that explicitly trusts the role from Account A" },
  { "front": "Which STS API do you use to integrate your Active Directory with AWS?", "back": "AssumeRoleWithSAML" },
  { "front": "How can you set up an on-prem Active Directory for use in multiple AWS accounts?", "back": "Use AWS IAM Identity Center, create an AWS Managed Directory, and create a two-way forest trust between your AD and the AWS Managed Directory" },
  { "front": "How can you limit specific services for an AWS account?", "back": "Create an AWS Organization and apply an SCP to the account" },
  { "front": "What is IAM Access Analyzer Policy Generation?", "back": "It automatically generates an IAM policy based on the activity of the resource, up to 90 days in the past." },
  { "front": "How can you easily create an IAM policy with least privilege on an existing resource?", "back": "Use IAM Access Analyzer Policy Generation" },
  { "front": "How can you move an AWS Member account from one AWS Organization A to another AWS Organization B?", "back": "Remove the account from Organization A. Send the invite to the account from Organization B. Accept the invite." },
  { "front": "Which EC2 instance type is not suported for integration with AWS IAM Identity Center?", "back": "EC2 Linux Instances" },
  { "front": "How can you control access management for EC2 Linux Instances?", "back": "The recommended approach is to use AWS Systems Manager (SSM) Session Manager or EC2 Instance Connect, rather than traditional SSH with IAM identities directly. " },
  { "front": "What is AWS Control Tower Account Factory?", "back": "A feature that automates the secure, governed creation and onboarding of new AWS accounts, acting like a self-service vending machine for standardized accounts within your organization." },
  { "front": "What are the 3 guardrails in AWS Control Tower?", "back": "Mandatory, Strongly Recommended, and Elective" },
  { "front": "Which AWS Service allows you to share resources between different AWS accounts?", "back": "AWS Resource Access Manager" },
  { "front": "What is AWS Resource Access Manager (AWS RAM)?", "back": "A service that simplifies securely sharing your AWS resources, like VPC subnets, Transit Gateways, or License Manager configurations, with other AWS accounts, organizational units (OUs), or your entire AWS Organization, reducing duplicate resource creation and operational overhead in multi-account environments." },
  { "front": "What is the recommended way of preventing Man In The Middle attacks?", "back": "Setup HTTPS and Route 53 DNSSEC." },
  { "front": "What is DNSSEC?", "back": "A suite of protocols that adds cryptographic signatures to DNS records." },
  { "front": "How do you deploy SSL Certificates to multiple ALBs, each in different regions?", "back": "Create a certificate in ACM in each region, and import each of them into their respective ALB" },
  { "front": "How can you limit access in a CloudHSM cluster?", "back": "Create an SSM parameter with the CloudHSM username/password for a user in CloudHSM that has access to specific keys. Create an IAM policy restricting access to that SSM parameter and attack the policy to the IAM user." },
  { "front": "What is an Elastic IP?", "back": "A static, public IPv4 address you can allocate to your account, providing a fixed internet-facing point for dynamic cloud resources like EC2 instances, remaining constant even if an instance stops/starts, and allowing quick remapping to another instance for failover, ensuring service availability with minimal downtime" },
  { "front": "How can you allow an EC2 instance in a public subnet that frequently starts and stops access to a specific resource?", "back": "Attach an Elastic IP to the EC2 instance and create a resource policy with a condition limiting access to the EC2 elastic IP." },
  { "front": "How can you block patterned HTTP requests?", "back": "Web Application Firewall (WAF)" },
  { "front": "What is AWS Web Application Firewall (WAF)?", "back": "A security service that protects web applications from common exploits and bots by filtering, monitoring, and blocking malicious HTTP/S traffic." },
  { "front": "What is AWS Shield?", "back": "A managed DDoS (Distributed Denial of Service) protection service that safeguards applications" },
  { "front": "What is a NACL?", "back": "Network Access Control List, an optional security layer that acts as a firewall for your Virtual Private Cloud (VPC) subnets, controlling inbound/outbound traffic with rules based on protocols, ports, and IP addresses, working at the subnet level, unlike Security Groups (SGs) which work at the instance level, and operating with stateless filtering (requiring explicit inbound/outbound rules).  " },
  { "front": "What are the 3 types of events CloudTrail has?", "back": "Management Events, Data Events, CloudTrail Insights" },
  { "front": "What are CloudTrail Management Events?", "back": "Operations that manage resources in your AWS account, such as creating users (IAM), modifying VPCs, or setting up trails." },
  { "front": "What are CloudTrail Data Events?", "back": "Resource-level operations, often high-volume, like getting, putting, or deleting objects in S3, or invoking Lambda functions." },
  { "front": "What are CloudTrail Insights Events?", "back": "Anomalous activity by analyzing management and data events to find unusual API call or error rate patterns." },
  { "front": "How can you store cryptographic keys that meet the FIPS 140-2 Level 3 security standard?", "back": "CloudHSM" },
  { "front": "How do you encrypt a Global DynamoDB table so that it uses the same KMS key in every region?", "back": "Use KMS Multi-Region Keys" },
  { "front": "What are KMS Multi-Region Keys?", "back": "a set of interoperable encryption keys, with the same key ID and material, replicated across different AWS Regions" },
  { "front": "What S3 encryption method allows for encryption outside of AWS?", "back": "Client-Side Encryption" },
  { "front": "What is SSE-S3 encryption?", "back": "An Amazon S3 feature that automatically encrypts data at rest using keys managed by S3 itself" },
  { "front": "What is SSE-KMS encryption?", "back": "An encryption method that encrypts data at rest using keys managed by AWS KMS" },
  { "front": "What is SSE-C encryption?", "back": "SSE-C (Server-Side Encryption with Customer-Provided Keys) is a cloud storage feature where you provide your own encryption keys to encrypt data at rest, giving you full control, while the cloud provider (like AWS S3, Cloudflare R2) handles the encryption/decryption process on the server side." },
  { "front": "What is Client-Side encryption?", "back": "The process of encrypting data locally, on the user's device, before it is uploaded to S3 buckets" },
  { "front": "Which feature in S3 allows you to get a detailed record for the requests that are made to the objects stored in your S3 bucket?", "back": "S3 Access Logs" },
  { "front": "What is S3 Access logs?", "back": "Detailed records that track all requests made to an S3 bucket, capturing information on who accessed what, when, and how" },
  { "front": "What is S3 Event Notifications?", "back": "A feature that sends real-time alerts about activities in your S3 buckets (like file uploads, deletions, or replication) to other AWS services, enabling automatic processing, workflows, and monitoring" },
  { "front": "How do you protect an application on AWS against layer 7 attacks?", "back": "AWS Web Application Firewall (WAF)" },
  { "front": "What is OSI model layer 1?", "back": "Physical Layer: Raw bits over physical media (cables, radio). " },
  { "front": "What is OSI model layer 2?", "back": "Data Link Layer: Frames data for same-network transmission, handles error control (Ethernet, MAC addresses). " },
  { "front": "What is OSI model layer 3?", "back": "Network Layer: Routes packets across different networks (IP, Routers). " },
  { "front": "What is OSI model layer 4?", "back": "Transport Layer: End-to-end data transfer, reliability (TCP, UDP, Port numbers). " },
  { "front": "What is OSI model layer 5?", "back": "Session Layer: Manages communication sessions, setup, and termination. " },
  { "front": "What is OSI model layer 6?", "back": "Presentation Layer: Data formatting, encryption, compression (ASCII, encryption). " },
  { "front": "What is OSI model layer 7?", "back": "Application Layer: Direct interface for user applications (HTTP, FTP, DNS). " },
  { "front": "What OSI model layer does TCP belong to?", "back": "OSI model layer 4" },
  { "front": "What OSI model layer does UDP belong to?", "back": "OSI model layer 4" },
  { "front": "What OSI model layer does HTTP/S belong to?", "back": "OSI model layer 7" },
  { "front": "What OSI model layer does FTP belong to?", "back": "OSI model layer 7" },
  { "front": "What OSI model layer does DNS) belong to?", "back": "OSI model layer 7" },
  { "front": "Which is NOT a supported destination for WAF Web ACLs logs?", "back": "Kinesis Data Streams" },
  { "front": "What is the key difference between Kinesis Data Streams and Kinesis Data Firehose?", "back": "The key difference is control vs. automation: Streams offers deep control and flexibility, whereas Firehose offers simplicity and automated delivery to various AWS services" },
  { "front": "What is AWS Firewall Manager?", "back": "A security management service that lets you centrally define, configure, and manage firewall rules and security policies (like AWS WAF, Shield Advanced, Network Firewall, VPC Security Groups, and DNS Firewall rules) across all your AWS accounts and applications within AWS Organizations." },
  { "front": "What service allows you to centrally define and apply WAF rules, security groups, AWS shield, etc. across multiple accounts?", "back": "AWS Firewall Manager" },
  { "front": "How can you periodically scan your EC2 instances against known vulnerabilities and exploits?", "back": "Amazon Inspector" },
  { "front": "What is Amazon Inspector?", "back": "An automated vulnerability management service that continually scans your AWS workloads (like EC2, Lambda, ECR containers) for software vulnerabilities and network exposure" },
  { "front": "What is Amazon Guard Duty?", "back": "a continuous threat detection service that monitors AWS accounts, workloads, and data for malicious activity and unauthorized behavior" },
  { "front": "What does Amazon Guard Duty scan?", "back": "CloudTrail Logs, VPC Flow Logs, DNS Logs, and Kubernetes Audit Logs" },
  { "front": "What does Amazon Guard Duty <strong>NOT</strong> scan?", "back": "AWS WAF Logs" },
  { "front": "What is the IAM Condition Key <code>aws:PrincipalOrgId</code> used for?", "back": "Used to restrict access from a specific AWS Organization" },
  { "front": "Which IAM Condition Key can you use to restrict access from a specific AWS Organization?", "back": "<code>aws:PrincipalOrgId</code>" },
  { "front": "What is a dedicated host?", "back": "A physical server in the Amazon EC2 infrastructure fully dedicated to a single customer's AWS account" },
  { "front": "What is host affinity?", "back": "a feature of Amazon EC2 Dedicated Hosts that lets you 'pin' an EC2 instance to a specific physical server" },
  { "front": "How can you run licensed software that requires dedicated physical cores or sockets on AWS?", "back": "Book a dedicated host, and use host affinity" },
  { "front": "You would like to automatically recover an EC2 instance in case of a fault on AWS side. How should you do it?", "back": "Create a CloudWatch alarm checking the EC2's underlying Cloudwatch Metrics. Trigger an EC2 instance recovery in case of issues." },
  { "front": "How do you ensure your ASG terminates unhealthy EC2 instances?", "back": "Add a <code>/health</code> endpoint on the EC2 instances that only checks the app status, NOT a DB connection or DB field" },
  { "front": "What is ECS Networking mode: <b>bridge</b>?", "back": "uses Docker's built-in virtual network, creating a software bridge on the host EC2 instance where containers get internal IPs and communicate via port mapping (container port to host port)" },
  { "front": "What is ECS Networking mode: <b>host</b>?", "back": "ties a container directly to the network of its underlying EC2 instance, sharing its network namespace, IP address, and interfaces, bypassing Docker's virtual networking for lower latency but sacrificing isolation and creating port conflicts" },
  { "front": "What is ECS Networking mode: <b>awsvpc</b>?", "back": "gives each task its own Elastic Network Interface (ENI) and private IP address within your Virtual Private Cloud (VPC), essentially treating each task like an independent EC2 instance for networking, allowing for fine-grained security group control, direct VPC integration, and support for features like ALB/NLB IP targets, but it can use more resources. " },
  { "front": "Which ECS networking mode gives each of your ECS tasks a different ENI?", "back": "<b>awsvpc</b>" },
  { "front": "How do you increase CPU on a lambda?", "back": "Incease the RAM on your lambda function" },
  { "front": "Which load balancer has cross-zone load balancing disabled by default?", "back": "Network Load Balancer (NLB), and enabling cross-zone load balancing incurs additional charges" },
  { "front": "What is the timeout for an API gateway?", "back": "29 seconds" },
  { "front": "What is Geolocation Route53 Record?", "back": "Routes traffic based on the user’s geographic location (country/continent), not latency." },
  { "front": "What is a Latency Route53 Record?", "back": "a special DNS record in Amazon Route 53 that uses a Latency-Based Routing Policy to direct user traffic to the AWS region with the lowest network latency, providing users with faster response times by sending them to the geographically closest or best-performing endpoint for that moment" },
  { "front": "What feature would you use to debug a EC2 instance that terminates randomly?", "back": "EC2 Lifecycle Hooks" },
  { "front": "What are EC2 Lifecycle Hooks?", "back": "features in AWS Auto Scaling that let you pause an instance during launch or termination to perform custom actions" },
  { "front": "How can you scan docker images before use in an AWS application?", "back": "Amazon ECR Image Scanning" },
  { "front": "What is Amazon ECR Image Scanning?", "back": "an automated vulnerability assessment feature for container images in the managed Amazon Elastic Container Registry (ECR) (ECR) that detects known security threats, like Common Vulnerabilities and Exposures (CVEs), within container images" },
  { "front": "Which node types does Amazon EKS support?", "back": "Self-Managed Nodes, Managed Node Groups, AWS Fargate" },
  { "front": "Which node types does Amazon EKS <b>NOT</b> support?", "back": "AWS Lambda" },
  { "front": "What is AWS App runner?", "back": "a fully managed container application service that makes it easy for developers to quickly deploy scalable and secure web applications and API services from source code or container images, without needing expertise in container orchestration or infrastructure management. " },
  { "front": "If your app is behind an ALB, how do you redirect traffic to use HTTPS instead of HTTP?", "back": "Configure the Application Load Balancer to redirect HTTP to HTTPS" },
  { "front": "Which Load Balancer should you use if you want to send traffic to an IDPS (intrusion detection and prevetion system) and/or a DPI (deep packet inspection)?", "back": "Gateway Load Balancer" },
  { "front": "What is a Gateway Load Balancer?", "back": "a cloud networking service that transparently inserts and scales virtual appliances like firewalls, intrusion detection systems (IDS), and deep packet inspection tools into your network traffic flow, which works on layer 3" },
  { "front": "What is AWS Global Accelerator?", "back": "A networking service that boosts the availability and performance of public applications for global users by routing traffic over the optimized AWS global network to the nearest healthy endpoint, using static IP addresses as fixed entry points for reliability and speed" },
  { "front": "Which AWS service can allow you to assign a static IP address and provide low latency across the globe?", "back": "AWS Global Accelerator" },
  { "front": "What is AWS Outposts?", "back": "brings managed AWS infrastructure and services directly to a customer's on-premises data center or edge location" },
  { "front": "Which AWS service allows you to use AWS but on-premises?", "back": "AWS Outposts" },
  { "front": "Which region do you create an ACM certificate for use with an API Gateway edge-optimized custom domain name?", "back": "<code>us-east-1</code>" },
  { "front": "Which region do you create an ACM certificate for use with an API Gateway Regional custom domain name?", "back": "The same region as your API Gateway" },
  { "front": "What is an API Gateway edge-optimized custom domain name?", "back": "a user-friendly and intuitive URL (e.g., api.example.com) that routes requests to an Amazon API Gateway API through the Amazon CloudFront global content delivery network (CDN)" },
  { "front": "What is an API Gateway Regional custom domain name?", "back": "provides a simple, branded, and intuitive URL for users to access an API endpoint deployed within a specific AWS Region. " },
  { "front": "How do you transfer an EBS volume between AZs?", "back": "Take a snapshot, restore the snapshot in the new AZ." },
  { "front": "What is the <code>gp2</code>/<code>gp3</code> EBS volume type?", "back": "General purpose SSD that balances price and performance" },
  { "front": "What is the <code>io1</code>/<code>io2</code> EBS volume type?", "back": "Highest-performance SSD volume for mission-critical low-latency or high-throughput workloads" },
  { "front": "What is the <code>st1</code> EBS volume type?", "back": "Low cost HDD volume designed for frequetly accessed throughput-intensive workloads" },
  { "front": "What is the <code>sc1</code> EBS volume type?", "back": "Lowest cost HDD volume designed for less frequently accessed workloads" },
  { "front": "What is the <code>sc1</code> EBS volume type?", "back": "Lowest cost HDD volume designed for less frequently accessed workloads" },
  { "front": "How can you increase the IOPS of a gp2 EBS volume?", "back": "Increase the EBS drive's size" },
  { "front": "What is the gp2 performance rule?", "back": "3 IOPS per GiB of volume size" },
  { "front": "What is Storage Gateway Volumes?", "back": "Stores and manages on-premises data in Amazon S3 on your behalf and operates in either cache mode or stored mode. In the cached Volume Gateway mode, your primary data is stored in Amazon S3, while retaining your frequently accessed data locally in the cache for low latency access." },
  { "front": "How do you get a POSIX networking file system for your on-premise VMs?", "back": "Provision EFS and connect through Direct Connect or Site-to-Site VPN" },
  { "front": "What is the most cost-efficient way of serving static content from AWS?", "back": "CloudFront + S3" },
  { "front": "How can you access part of a file in S3?", "back": "Use an S3 byte-range fetch" },
  { "front": "What is EFS Cross-region replication?", "back": "provides a powerful way to maintain synchronized copies of your file systems across different AWS regions" },
  { "front": "What is an AWS S3 Access Point?", "back": "A named entity with specific permissions that simplifies managing data access for shared datasets in Amazon S3, allowing you to create unique access policies for different applications or teams without complex bucket policies, and can enforce network controls like VPC restrictions" },
  { "front": "What is FSx?", "back": "a managed cloud file storage service for high-performance needs" },
  { "front": "What is FSx for Lustre?", "back": "a fully managed, high-performance file storage service on AWS, built on the popular open-source Lustre file system, designed for demanding, compute-intensive workloads like machine learning, High-Performance Computing (HPC), and video processing, offering petabyte-scale storage, millions of IOPS, and high throughput with sub-millisecond latency, easily integrating with Amazon S3 for data lakes and cost optimization. " },
  { "front": "What is FSx for Windows File Server?", "back": "provides fully managed, highly reliable, and scalable file storage in the cloud, built on native Windows Server and accessible via the industry-standard SMB protocol, making it ideal for 'lift-and-shift' of Windows applications needing shared storage like CRM, ERP, or home directories" },
  { "front": "What is FSx for OpenZFS?", "back": "a fully managed Amazon Web Services (AWS) file storage service that lets you run the powerful, open-source OpenZFS file system on AWS without managing the underlying infrastructure" },
  { "front": "What is FSx for NetApp ONTAP?", "back": "a fully managed cloud file storage service in Amazon Web Services (AWS) that runs NetApp ONTAP file systems in the AWS cloud" },
  { "front": "Which flavor of FSx is best suited for machine learning and hich-performance computing (HPC)?", "back": "FSx for Lustre" },
  { "front": "What is the best way to decrease the size of a file system of type FSx for Windows File Server?", "back": "Provision a new FSx for Windows file system and use AWS DataSync to move the data to the new file system" },
  { "front": "What is AWS DataSync?", "back": "a secure, online data transfer service that simplifies, automates, and accelerates moving large amounts of data between on-premises storage, other cloud providers, and various AWS storage services like S3, EFS, and FSx" },
  { "front": "Which AWS service is best suited to migrate a large amount of data from an S3 bucket to an EFS file system?", "back": "AWS DataSync" },
  { "front": "What is AWS Transfer Family?", "back": "a fully managed AWS service for securely transferring files into and out of Amazon S3 and EFS using standard protocols like SFTP, FTPS, FTP, and AS2" },
  { "front": "Amazon FSx for NetApp ONTAP is compatible with which protocols?", "back": "NFS, SMB, and iSCSI" },
  { "front": "Amazon FSx for NetApp ONTAP is <b>NOT</b> compatible with which protocol?", "back": "FTP" },
  { "front": "Which AWS service is best suited when migrating from an on-premises ZFS file system to AWS?", "back": "Amazon FSx for OpenZFS" },
  { "front": "If you have the same SSL certificate on your CloudFront and ALB, how do you preserve SSL?", "back": "Forward the <code>Host</code> header" },
  { "front": "How do you ensure your ALB is only accessible through a CloudFront distribution?", "back": "Make your ALB public. Create a CloudFront VPC Origins and attach it to your ALB and create CloudFront signed URLs. Private ALB cannot be reached by CloudFront." },
  { "front": "What is CloudFront VPC Origins?", "back": "CloudFront VPC Origins allow CloudFront to access private origins such as NLBs or EC2 instances in a VPC via PrivateLink." },
  { "front": "What are CloudFront signed URLs?", "back": "temporary, secure links that grant limited access to private content on Amazon CloudFront, using cryptographic signatures and access policies (like expiration times or IP restrictions) to control who can view specific files, ideal for individual downloads or when cookies aren't supported" },
  { "front": "Which ElastiCache technology will give you a deployment that can survive the loss of an AZ without data loss?", "back": "Redis" },
  { "front": "What is ElastiCache Redis?", "back": "Amazon Web Services' (AWS) fully managed, in-memory caching service built on open-source Redis, designed to provide high-performance, scalable data storage and caching with sub-millisecond latency" },
  { "front": "What is ElastiCache Memcached?", "back": "a fully managed, high-performance, in-memory caching service from AWS that provides a Memcached-compatible key-value store to accelerate applications by storing frequently accessed data in memory for sub-millisecond access, offloading databases, and simplifying scaling with features like auto-discovery and cluster management" },
  { "front": "What is the difference between ElastiCache Redis and ElastiCache Memcached?", "back": "ElastiCache Redis is a feature-rich, data-structure-supporting in-memory store with persistence and advanced features like Pub/Sub, while Memcached offers a simpler, multi-threaded key-value cache ideal for basic object caching" },
  { "front": "What are CloudFront Price Classes?", "back": "AWS settings that let you control costs by choosing which groups (or 'classes') of edge locations serve your content, balancing performance and price" },
  { "front": "What is CloudFront Cache Invalidation?", "back": "a process to force Amazon CloudFront to remove (invalidate) specific files from its global edge locations before their standard Time-to-Live (TTL) expires" },
  { "front": "What is CloudFront Cache Behavior?", "back": "defines rules for how Amazon CloudFront handles requests, controlling which origin gets the content, how long it's cached (TTL), which HTTP methods are allowed, and if query strings or cookies affect the cache, all based on URL path patterns" },
  { "front": "What is Origin Access Control?", "back": "an Amazon CloudFront feature that securely controls access to your content origins (like S3 buckets or Lambda function URLs) by ensuring only your specified CloudFront distributions can fetch content, preventing direct access via origin URLs and improving security with AWS Signature Version 4 (SigV4)" },
  { "front": "What is CloudFront Geo Restriction?", "back": "an AWS feature that lets you control content access by location, allowing you to block or allow users from specific countries from reaching your content served through the Amazon CloudFront Content Delivery Network (CDN)" },
  { "front": "What are CloudFront Origin Groups?", "back": "create a primary and secondary origin with failover rules, allowing CloudFront to automatically switch to the secondary origin if the primary fails" },
  { "front": "How can you decrease latency when you are serving files from multiple S3 buckets in different regions using CloudFront?", "back": "Create a Lambda@Edge function to inspect the request header and route the request to the nearest S3 bucket" },
  { "front": "What is the NFS protocol?", "back": "a distributed file system that lets users access files and folders on a remote server as if they were local" },
  { "front": "What is the SMB protocol?", "back": "a network communication protocol that allows computers to share files, printers, and other resources (like serial ports) over a network, primarily in Windows environments but also used by Linux/Unix via Samba" },
  { "front": "What is the iSCSI protocol?", "back": "a protocol that lets SCSI commands (for block storage) travel over standard TCP/IP networks, effectively extending storage area networks (SANs) over Ethernet, the internet, or LANs/WANs" }
];

/*
,
  { "front": "", "back": "" }
*/