# Generated by Django 4.1.3 on 2022-12-25 03:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousLoginFailure',
            fields=[
                ('hash', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Random UUID representing this failure entry')),
                ('time_stamp', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='time the user last failed')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
